"""Creación inicial de todas las tablas académicas

Revision ID: 539409801079
Revises: 
Create Date: 2025-12-05 08:36:50.386194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539409801079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('evaluation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('curriculum_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrera_id', 'materia_id', 'semestre_id', name='_curriculum_uc')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('estado_actual', sa.String(length=20), nullable=False),
    sa.Column('riesgo_desercion', sa.Float(), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('ingreso_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['ingreso_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('academic_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('ausencias', sa.Integer(), nullable=False),
    sa.Column('estatus_final', sa.String(length=50), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('año_id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['año_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['evaluation_type_id'], ['evaluation_types.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'materia_id', 'año_id', 'semestre_id', 'evaluation_type_id', name='_record_evaluation_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_records')
    op.drop_table('students')
    op.drop_table('curriculum_courses')
    op.drop_table('semesters')
    op.drop_table('majors')
    op.drop_table('evaluation_types')
    op.drop_table('courses')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
