"""Estructura final de AcademicRecord con flag is_cinco_felicitado

Revision ID: 9f5cc43ebea5
Revises: ba1f712c88a7
Create Date: 2025-12-09 10:00:59.966899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5cc43ebea5'
down_revision = 'ba1f712c88a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cinco_felicitado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.drop_column('is_cinco_felicitado')

    # ### end Alembic commands ###
