"""Añadir campo sexo a tabla Student

Revision ID: ba1f712c88a7
Revises: 539409801079
Create Date: 2025-12-09 07:28:08.644195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1f712c88a7'
down_revision = '539409801079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.Integer(), nullable=False))
        batch_op.drop_column('riesgo_desercion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('riesgo_desercion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
